### DISCUSSION TITLE
How did you use git action cron?

### DISCUSSION THREAD

**Discussion by closh** [ifntsh/airflow#3] [Q&A] [answered]
How did you use git action cron?

**Comment by ifntsh** [comment, marked as answer]
```
name: lunch-noti

on:
  schedule:
    # KST 오전 11시 30분 -> UTC 오전 2시 30분, 평일에만 돌아감
    # - cron: "25 2 * * 1-5"
    - cron: "*/1 * * * 1-5"
  workflow_dispatch:

```
I used it as above, but it's not going as well as I wanted.
